# Assignment 3_LI XINYA

### Import the libraries

In [1]:
import pandas as pd
import numpy as np
import torch
import torchvision
import math

### Define the Input:

In [2]:
# 32x32 pixels, 3 channels
Input = torch.randn(1,3,32,32)
Input

tensor([[[[ 2.1981e+00, -4.6451e-01, -1.5665e-01,  ...,  3.5825e-01,
            5.0774e-01,  6.4651e-01],
          [-6.8014e-01, -1.4383e+00, -4.7001e-01,  ..., -1.5630e+00,
           -2.5450e-01, -3.2320e-01],
          [ 1.3550e+00,  1.2372e-01, -4.8353e-01,  ..., -1.0282e+00,
           -2.1841e+00, -1.1347e-01],
          ...,
          [-3.4027e-01,  4.8877e-01, -2.0639e-01,  ..., -5.6422e-01,
            6.6676e-01,  2.8339e-01],
          [ 1.8143e+00,  9.3710e-01, -4.6415e-01,  ..., -3.8587e-01,
            5.3576e-01,  1.0744e+00],
          [-1.0109e+00, -1.2394e-01,  1.0173e+00,  ..., -4.1536e-01,
           -1.1075e+00, -7.1288e-01]],

         [[-5.3218e-01,  2.2225e-01,  1.6399e+00,  ..., -2.1652e+00,
           -1.6121e+00, -1.9405e+00],
          [ 6.0333e-01,  2.0236e-01,  2.1709e-01,  ...,  9.9807e-01,
            5.7821e-01, -1.3940e-03],
          [-8.1933e-01,  1.1584e+00, -8.7382e-01,  ...,  5.6400e-01,
           -5.0604e-01,  2.8894e-01],
          ...,
     

## Function 1: torch.nn.MaxPool2d

In [3]:
# using pytorch
layer_1 = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, return_indices=False, ceil_mode=False)
output_1 = layer_1(Input)
output_1

tensor([[[[ 2.1981, -0.1567,  1.0647,  ...,  1.1957,  0.5077,  0.6465],
          [ 1.3550,  0.1237, -0.1990,  ...,  0.2669, -0.2545, -0.1135],
          [ 1.3550,  0.1237,  0.0666,  ...,  0.2669,  1.8966,  1.8966],
          ...,
          [ 1.0952,  1.0952,  0.1387,  ...,  0.3140,  0.6668,  0.6668],
          [ 1.8143,  0.9371, -0.0184,  ..., -0.0688,  0.6668,  1.0744],
          [ 1.8143,  1.0173,  1.0173,  ..., -0.0688,  0.5358,  1.0744]],

         [[ 0.6033,  1.6399,  1.6399,  ...,  0.9981,  0.9981,  0.5782],
          [ 1.1584,  1.1584,  0.6733,  ...,  0.9981,  0.9981,  0.5782],
          [ 1.1584,  1.1584,  1.3359,  ...,  0.8254,  0.8254,  0.2889],
          ...,
          [ 0.6181,  0.0914,  1.0566,  ...,  0.3681,  0.9976,  0.9976],
          [-0.0135,  0.0942,  0.5793,  ...,  0.4086,  0.4086,  1.5426],
          [ 0.6724,  0.0942,  1.9908,  ...,  0.4086,  0.4086,  1.5426]],

         [[ 0.2711,  0.2711,  0.9275,  ...,  0.8220,  0.8220,  0.6302],
          [ 0.6000,  0.3127,  

In [4]:
def max_pooling(x, pool_param):
    out = None
    N, C, H, W = x.shape
    HH, WW = pool_param['pool_height'], pool_param['pool_width']
    stride = pool_param['stride']
  
    H_out = 1 + (H - HH) // stride
    W_out = 1 + (W - WW) // stride
  
    out = torch.zeros((N, C, H_out, W_out), device=x.device, dtype=x.dtype)
    for img in range(N):
        for channel in range(C):
            for i in range(H_out):
                for j in range(W_out):
                    out[img, channel, i, j] = torch.max(x[img, channel, i*stride:i*stride+HH, j*stride:j*stride+WW])
    cache = (x, pool_param)
    return out

In [5]:
pool_param = {'pool_width': 2, 'pool_height': 2, 'stride': 1}
output_1_ = max_pooling(Input,pool_param)
output_1_

tensor([[[[ 2.1981, -0.1567,  1.0647,  ...,  1.1957,  0.5077,  0.6465],
          [ 1.3550,  0.1237, -0.1990,  ...,  0.2669, -0.2545, -0.1135],
          [ 1.3550,  0.1237,  0.0666,  ...,  0.2669,  1.8966,  1.8966],
          ...,
          [ 1.0952,  1.0952,  0.1387,  ...,  0.3140,  0.6668,  0.6668],
          [ 1.8143,  0.9371, -0.0184,  ..., -0.0688,  0.6668,  1.0744],
          [ 1.8143,  1.0173,  1.0173,  ..., -0.0688,  0.5358,  1.0744]],

         [[ 0.6033,  1.6399,  1.6399,  ...,  0.9981,  0.9981,  0.5782],
          [ 1.1584,  1.1584,  0.6733,  ...,  0.9981,  0.9981,  0.5782],
          [ 1.1584,  1.1584,  1.3359,  ...,  0.8254,  0.8254,  0.2889],
          ...,
          [ 0.6181,  0.0914,  1.0566,  ...,  0.3681,  0.9976,  0.9976],
          [-0.0135,  0.0942,  0.5793,  ...,  0.4086,  0.4086,  1.5426],
          [ 0.6724,  0.0942,  1.9908,  ...,  0.4086,  0.4086,  1.5426]],

         [[ 0.2711,  0.2711,  0.9275,  ...,  0.8220,  0.8220,  0.6302],
          [ 0.6000,  0.3127,  

In [6]:
# check the difference
print(torch.allclose(output_1, output_1_))

True


## Function 2: torch.nn.AvgPool2d

In [7]:
# using pytorch
layer_2 = torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0,ceil_mode=False, count_include_pad=True,divisor_override=None)
output_2 = layer_2(Input)
output_2

tensor([[[[-0.0962, -0.6324,  0.0597,  ..., -0.2484, -0.2379,  0.1441],
          [-0.1599, -0.5670, -0.5114,  ..., -0.8272, -1.2575, -0.7188],
          [ 0.3953, -0.3254, -0.4904,  ..., -0.5710, -0.4807, -0.1909],
          ...,
          [ 0.1686,  0.3791, -0.0900,  ..., -0.3786, -0.1874, -0.4608],
          [ 0.7250,  0.1888, -0.2262,  ..., -0.6288,  0.0631,  0.6401],
          [ 0.4041,  0.3416,  0.1189,  ..., -0.3423, -0.3432, -0.0525]],

         [[ 0.1239,  0.5704,  0.1647,  ..., -0.9639, -0.5503, -0.7439],
          [ 0.2862,  0.1760, -0.1523,  ..., -0.3240,  0.4086,  0.0899],
          [-0.2203, -0.1824,  0.2161,  ...,  0.1222, -0.2320, -0.4706],
          ...,
          [-0.6109, -0.5306,  0.1321,  ..., -0.0552,  0.1582,  0.0435],
          [-0.7216, -0.3260,  0.1702,  ..., -0.1927, -0.1447, -0.0834],
          [-0.2045, -0.3591,  0.6527,  ..., -0.7084, -0.5802,  0.0326]],

         [[-0.6458, -0.5365, -0.3810,  ...,  0.4611, -0.0472, -0.2524],
          [-0.4646, -0.4910, -

In [8]:
def avg_pooling(x, pool_param):
    out = None
    N, C, H, W = x.shape
    HH, WW = pool_param['pool_height'], pool_param['pool_width']
    stride = pool_param['stride']
  
    H_out = 1 + (H - HH) // stride
    W_out = 1 + (W - WW) // stride
  
    out = torch.zeros((N, C, H_out, W_out), device=x.device, dtype=x.dtype)
    for img in range(N):
        for channel in range(C):
            for i in range(H_out):
                for j in range(W_out):
                    out[img, channel, i, j] = torch.mean(x[img, channel, i*stride:i*stride+HH, j*stride:j*stride+WW])
    return out

In [9]:
pool_param = {'pool_width': 2, 'pool_height': 2, 'stride': 1}
output_2_ = avg_pooling(Input,pool_param)
output_2_

tensor([[[[-0.0962, -0.6324,  0.0597,  ..., -0.2484, -0.2379,  0.1441],
          [-0.1599, -0.5670, -0.5114,  ..., -0.8272, -1.2575, -0.7188],
          [ 0.3953, -0.3254, -0.4904,  ..., -0.5710, -0.4807, -0.1909],
          ...,
          [ 0.1686,  0.3791, -0.0900,  ..., -0.3786, -0.1874, -0.4608],
          [ 0.7250,  0.1888, -0.2262,  ..., -0.6288,  0.0631,  0.6401],
          [ 0.4041,  0.3416,  0.1189,  ..., -0.3423, -0.3432, -0.0525]],

         [[ 0.1239,  0.5704,  0.1647,  ..., -0.9639, -0.5503, -0.7439],
          [ 0.2862,  0.1760, -0.1523,  ..., -0.3240,  0.4086,  0.0899],
          [-0.2203, -0.1824,  0.2161,  ...,  0.1222, -0.2320, -0.4706],
          ...,
          [-0.6109, -0.5306,  0.1321,  ..., -0.0552,  0.1582,  0.0435],
          [-0.7216, -0.3260,  0.1702,  ..., -0.1927, -0.1447, -0.0834],
          [-0.2045, -0.3591,  0.6527,  ..., -0.7084, -0.5802,  0.0326]],

         [[-0.6458, -0.5365, -0.3810,  ...,  0.4611, -0.0472, -0.2524],
          [-0.4646, -0.4910, -

In [10]:
# check the difference
print(torch.allclose(output_2, output_2_))

True


## Function 3: torch.nn.Conv2d
## stride=1

In [11]:
layer_3 = torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=3, stride=1, padding=0, dilation=1, groups=1,bias=True, padding_mode="zeros")
output_3_1 = layer_3(Input)
output_3_1                      

tensor([[[[ 8.7203e-01, -4.4504e-01,  2.1526e-01,  ...,  9.4919e-01,
           -1.0656e-01, -5.6796e-01],
          [-6.9558e-01,  4.4238e-01,  3.1154e-01,  ...,  8.8952e-01,
           -3.4418e-01,  4.8535e-01],
          [ 1.2032e+00, -3.5157e-01,  1.1570e-02,  ...,  4.8008e-01,
            8.7856e-02, -4.4224e-01],
          ...,
          [-5.6077e-01, -3.2963e-01, -4.2985e-01,  ..., -1.0816e-01,
           -2.6410e-01, -2.7346e-01],
          [-2.4182e-02,  8.9218e-02, -1.4849e-01,  ...,  2.1303e-01,
            2.9281e-03, -1.5736e-01],
          [ 2.4689e-01,  1.0195e-01,  6.4096e-01,  ...,  3.6735e-01,
           -4.6341e-01, -5.6703e-01]],

         [[-4.1867e-01,  1.6466e-01, -5.7732e-03,  ...,  2.0410e-01,
           -2.3797e-01,  1.3518e-01],
          [ 3.2239e-01,  8.8653e-01,  4.9060e-01,  ...,  1.1738e+00,
            1.8581e-01,  1.0463e-01],
          [ 1.4067e-01, -6.8316e-01,  7.2514e-01,  ...,  1.3588e-01,
            7.7709e-01, -3.8446e-01],
          ...,
     

In [12]:
def conv2d(x, w, b, conv_param):
    out = None
    padding = torch.nn.functional.pad
    pad = conv_param['pad']
    stride = conv_param['stride']
    N, C, H, W = x.shape
    F, _, HH, WW = w.shape
  
    H_out = 1 + (H + 2 * pad - HH) // stride
    W_out = 1 + (W + 2 * pad - WW) // stride
    out = torch.zeros((N, F, H_out, W_out), device = x.device, dtype= x.dtype)
  
    x_pad = padding(x, (pad, pad, pad, pad), mode='constant', value=0) 
    for image in range(N): # each image
        for flr in range(F): # for each filter
            for i in range(H_out): # row
                for j in range(W_out): # column
                    out[image, flr, i, j] = torch.sum(x_pad[image, : , i*stride:i*stride+HH, j*stride:j*stride+WW] * w[flr, :, :, :]) + b[flr]
    return out

In [13]:
conv_param = {'stride': 1, 'pad': 0}
output_3_1_ = conv2d(Input, layer_3.weight, layer_3.bias, conv_param)
output_3_1_

tensor([[[[ 8.7203e-01, -4.4504e-01,  2.1526e-01,  ...,  9.4919e-01,
           -1.0656e-01, -5.6796e-01],
          [-6.9558e-01,  4.4238e-01,  3.1154e-01,  ...,  8.8952e-01,
           -3.4418e-01,  4.8535e-01],
          [ 1.2032e+00, -3.5157e-01,  1.1570e-02,  ...,  4.8008e-01,
            8.7856e-02, -4.4224e-01],
          ...,
          [-5.6077e-01, -3.2963e-01, -4.2985e-01,  ..., -1.0816e-01,
           -2.6410e-01, -2.7346e-01],
          [-2.4182e-02,  8.9218e-02, -1.4849e-01,  ...,  2.1303e-01,
            2.9281e-03, -1.5736e-01],
          [ 2.4689e-01,  1.0195e-01,  6.4096e-01,  ...,  3.6735e-01,
           -4.6341e-01, -5.6703e-01]],

         [[-4.1867e-01,  1.6466e-01, -5.7732e-03,  ...,  2.0410e-01,
           -2.3797e-01,  1.3518e-01],
          [ 3.2239e-01,  8.8653e-01,  4.9060e-01,  ...,  1.1738e+00,
            1.8581e-01,  1.0463e-01],
          [ 1.4067e-01, -6.8316e-01,  7.2514e-01,  ...,  1.3588e-01,
            7.7709e-01, -3.8446e-01],
          ...,
     

In [41]:
error_3_1 = torch.nn.functional.mse_loss(output_3_1,output_3_1_)
error_3_1

tensor(4.1442e-15, grad_fn=<MseLossBackward>)

## stride=2

In [38]:
layer_3_ = torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=5, stride=2, padding=0, dilation=1, groups=1,bias=True, padding_mode="zeros")
output_3_2 = layer_3_(Input)
output_3_2 

tensor([[[[-7.2649e-01,  2.0261e-01,  1.1391e-01,  ...,  1.3773e-01,
            6.1435e-01, -8.8689e-01],
          [-5.2798e-01,  9.7485e-02, -5.7463e-02,  ...,  5.3853e-01,
            3.8538e-01, -4.6062e-01],
          [ 3.2571e-01,  6.9098e-01, -5.2618e-01,  ..., -1.2193e-01,
           -6.2236e-01, -5.9790e-01],
          ...,
          [-4.2108e-01,  6.6336e-01, -3.1995e-01,  ..., -3.5456e-01,
           -4.8147e-01,  4.6441e-01],
          [-2.1431e-01,  5.7067e-02,  1.4685e-01,  ...,  3.4145e-02,
            4.8186e-01,  6.5116e-01],
          [-2.4994e-01,  5.0221e-01, -1.9064e-01,  ..., -2.7203e-02,
            1.0383e+00, -4.9113e-01]],

         [[ 5.6631e-01, -4.0139e-02, -8.1993e-01,  ...,  6.7218e-01,
            2.4324e-01, -8.6569e-01],
          [ 7.9102e-02,  1.1307e+00,  2.7271e-01,  ...,  4.3627e-01,
           -9.5368e-01, -1.0314e-01],
          [-4.0247e-01, -1.3317e-01, -1.0286e-01,  ...,  3.6873e-01,
           -3.4189e-01,  4.0420e-01],
          ...,
     

In [39]:
conv_param = {'stride': 2, 'pad': 0}
output_3_2_ = conv2d(Input, layer_3_.weight, layer_3_.bias, conv_param)
output_3_2_

tensor([[[[-7.2649e-01,  2.0261e-01,  1.1391e-01,  ...,  1.3773e-01,
            6.1435e-01, -8.8689e-01],
          [-5.2798e-01,  9.7485e-02, -5.7463e-02,  ...,  5.3853e-01,
            3.8538e-01, -4.6062e-01],
          [ 3.2571e-01,  6.9098e-01, -5.2618e-01,  ..., -1.2193e-01,
           -6.2236e-01, -5.9790e-01],
          ...,
          [-4.2108e-01,  6.6335e-01, -3.1995e-01,  ..., -3.5456e-01,
           -4.8147e-01,  4.6441e-01],
          [-2.1431e-01,  5.7067e-02,  1.4685e-01,  ...,  3.4145e-02,
            4.8186e-01,  6.5116e-01],
          [-2.4994e-01,  5.0221e-01, -1.9064e-01,  ..., -2.7203e-02,
            1.0383e+00, -4.9113e-01]],

         [[ 5.6631e-01, -4.0139e-02, -8.1993e-01,  ...,  6.7218e-01,
            2.4324e-01, -8.6569e-01],
          [ 7.9102e-02,  1.1307e+00,  2.7271e-01,  ...,  4.3627e-01,
           -9.5368e-01, -1.0314e-01],
          [-4.0247e-01, -1.3317e-01, -1.0286e-01,  ...,  3.6873e-01,
           -3.4189e-01,  4.0420e-01],
          ...,
     

In [42]:
error_3_2 = torch.nn.functional.mse_loss(output_3_2,output_3_2_)
error_3_2

tensor(9.2051e-15, grad_fn=<MseLossBackward>)

## Function 4: torch.nn.ConvTranspose2d

In [61]:
layer_4 = torch.nn.ConvTranspose2d(in_channels=3, out_channels=4,kernel_size=3, stride=1, padding=0, output_padding=0,groups=1, bias=True, dilation=1, padding_mode='zeros')
output_4 = layer_4(Input)
output_4

tensor([[[[ 0.0504,  0.5800,  0.2070,  ...,  0.1275,  0.0638,  0.1048],
          [-0.0216,  0.4826, -0.2618,  ...,  0.4198,  0.0998,  0.1133],
          [-0.3666,  0.9423, -0.2220,  ..., -0.1946, -0.0681, -0.0588],
          ...,
          [-0.0938,  0.5015,  0.4664,  ...,  0.0483,  0.1389, -0.3200],
          [ 0.3685,  0.3206, -0.4306,  ...,  0.3167, -0.3360,  0.2729],
          [ 0.1233, -0.2338,  0.3841,  ..., -0.0300,  0.4937,  0.0741]],

         [[ 0.0635,  0.2854, -0.0904,  ...,  0.5334,  0.2433,  0.2862],
          [-0.0519, -0.3673, -0.6038,  ...,  0.3755,  0.1489,  0.2816],
          [ 0.1492,  0.0312,  0.7939,  ...,  0.0651,  0.2043,  0.1165],
          ...,
          [ 0.4137, -0.3179, -0.4402,  ..., -0.4524, -0.2799, -0.0806],
          [-0.0829, -0.0312,  0.8366,  ...,  0.3287,  0.6308,  0.2726],
          [ 0.1903,  0.2443, -0.1163,  ...,  0.3826, -0.0642,  0.0931]],

         [[ 0.0629,  0.1590,  0.2495,  ...,  0.0082,  0.3712,  0.0030],
          [ 0.4158, -0.2845, -

In [68]:
def trans(x, weight, bias, channel):
    h = weight.shape[2]
    w = weight.shape[3]
    out = torch.zeros((1, x.shape[1] + h - 1, x.shape[2] + w - 1))
    for k in range(x.shape[0]):
        for i in range(x.shape[1]):
            for j in range(x.shape[2]):
                out[0,i:i + h, j:j + w] += x[k, i, j] * weight[k][channel]
    out += bias[channel]
    return out
def trans_conv(x, weight, bias, out_channel):
    result = []
    
    for i in range(out_channel):
        out = trans(x, weight, bias, i)
        result.append(out[0])
    return torch.stack(result,dim = 0)

In [71]:
output_4_ = trans_conv(Input[0], layer_4.weight, layer_4.bias, layer_4.out_channels)
output_4_

tensor([[[ 0.0504,  0.5800,  0.2070,  ...,  0.1275,  0.0638,  0.1048],
         [-0.0216,  0.4826, -0.2618,  ...,  0.4198,  0.0998,  0.1133],
         [-0.3666,  0.9423, -0.2220,  ..., -0.1946, -0.0681, -0.0588],
         ...,
         [-0.0938,  0.5015,  0.4664,  ...,  0.0483,  0.1389, -0.3200],
         [ 0.3685,  0.3206, -0.4306,  ...,  0.3167, -0.3360,  0.2729],
         [ 0.1233, -0.2338,  0.3841,  ..., -0.0300,  0.4937,  0.0741]],

        [[ 0.0635,  0.2854, -0.0904,  ...,  0.5334,  0.2433,  0.2862],
         [-0.0519, -0.3673, -0.6038,  ...,  0.3755,  0.1489,  0.2816],
         [ 0.1492,  0.0312,  0.7939,  ...,  0.0651,  0.2043,  0.1165],
         ...,
         [ 0.4137, -0.3179, -0.4402,  ..., -0.4524, -0.2799, -0.0806],
         [-0.0829, -0.0312,  0.8366,  ...,  0.3287,  0.6308,  0.2726],
         [ 0.1903,  0.2443, -0.1163,  ...,  0.3826, -0.0642,  0.0931]],

        [[ 0.0629,  0.1590,  0.2495,  ...,  0.0082,  0.3712,  0.0030],
         [ 0.4158, -0.2845, -0.0636,  ...,  0

In [72]:
error_4 = torch.nn.functional.mse_loss(output_4[0],output_4_)
error_4

tensor(2.7919e-15, grad_fn=<MseLossBackward>)

## Function 5: torch.flatten

In [19]:
output_5 = torch.flatten(Input, start_dim=0, end_dim=-1)
output_5

tensor([ 2.1981, -0.4645, -0.1567,  ..., -0.5632,  0.7777, -0.7101])

In [20]:
def Flatten(inp):
    flatten_list = []
    for i in inp:
        for j in i:
            for h in j:  
                for w in h:
                    flatten_list.append(w)
    return torch.tensor(np.array(flatten_list))

In [21]:
output_5_ = Flatten(Input)
output_5_

tensor([ 2.1981, -0.4645, -0.1567,  ..., -0.5632,  0.7777, -0.7101])

In [50]:
error_5 = torch.nn.functional.mse_loss(output_5,output_5_)
error_5

tensor(0.)

## Function 6: torch.sigmoid

In [22]:
output_6 = torch.sigmoid(Input, out=None)
output_6

tensor([[[[0.9001, 0.3859, 0.4609,  ..., 0.5886, 0.6243, 0.6562],
          [0.3362, 0.1918, 0.3846,  ..., 0.1732, 0.4367, 0.4199],
          [0.7949, 0.5309, 0.3814,  ..., 0.2634, 0.1012, 0.4717],
          ...,
          [0.4157, 0.6198, 0.4486,  ..., 0.3626, 0.6608, 0.5704],
          [0.8599, 0.7185, 0.3860,  ..., 0.4047, 0.6308, 0.7454],
          [0.2668, 0.4691, 0.7344,  ..., 0.3976, 0.2483, 0.3290]],

         [[0.3700, 0.5553, 0.8375,  ..., 0.1029, 0.1663, 0.1256],
          [0.6464, 0.5504, 0.5541,  ..., 0.7307, 0.6407, 0.4997],
          [0.3059, 0.7610, 0.2945,  ..., 0.6374, 0.3761, 0.5717],
          ...,
          [0.2005, 0.3660, 0.5228,  ..., 0.4151, 0.4547, 0.2259],
          [0.4966, 0.2808, 0.5235,  ..., 0.6007, 0.3863, 0.8238],
          [0.6620, 0.3690, 0.4866,  ..., 0.1231, 0.4248, 0.3439]],

         [[0.3575, 0.5674, 0.4181,  ..., 0.5938, 0.3809, 0.6525],
          [0.1615, 0.3495, 0.1877,  ..., 0.6947, 0.2881, 0.4380],
          [0.6457, 0.4526, 0.5775,  ..., 0

In [52]:
def Sigmoid (inp):
    output = 1.0 / (1.0 + np.exp(-inp))
    return output
    
output_6_ = Sigmoid (Input)
output_6_

tensor([[[[0.9001, 0.3859, 0.4609,  ..., 0.5886, 0.6243, 0.6562],
          [0.3362, 0.1918, 0.3846,  ..., 0.1732, 0.4367, 0.4199],
          [0.7949, 0.5309, 0.3814,  ..., 0.2634, 0.1012, 0.4717],
          ...,
          [0.4157, 0.6198, 0.4486,  ..., 0.3626, 0.6608, 0.5704],
          [0.8599, 0.7185, 0.3860,  ..., 0.4047, 0.6308, 0.7454],
          [0.2668, 0.4691, 0.7344,  ..., 0.3976, 0.2483, 0.3290]],

         [[0.3700, 0.5553, 0.8375,  ..., 0.1029, 0.1663, 0.1256],
          [0.6464, 0.5504, 0.5541,  ..., 0.7307, 0.6407, 0.4997],
          [0.3059, 0.7610, 0.2945,  ..., 0.6374, 0.3761, 0.5717],
          ...,
          [0.2005, 0.3660, 0.5228,  ..., 0.4151, 0.4547, 0.2259],
          [0.4966, 0.2808, 0.5235,  ..., 0.6007, 0.3863, 0.8238],
          [0.6620, 0.3690, 0.4866,  ..., 0.1231, 0.4248, 0.3439]],

         [[0.3575, 0.5674, 0.4181,  ..., 0.5938, 0.3809, 0.6525],
          [0.1615, 0.3495, 0.1877,  ..., 0.6947, 0.2881, 0.4380],
          [0.6457, 0.4526, 0.5775,  ..., 0

In [53]:
error_6 = torch.nn.functional.mse_loss(output_6,output_6_)
error_6

tensor(0.)

## Function 7: torchvision.ops.roi_pool

In [64]:
box = torch.tensor([[0,0,0,31,31]]).float()
output_7 = torchvision.ops.roi_pool(Input, box,output_size=(8,8))
output_7

tensor([[[[2.1981, 1.9790, 1.6071, 2.0625, 1.0465, 0.8380, 2.3753, 1.8966],
          [1.2296, 1.9685, 2.0244, 2.4132, 3.0291, 1.6265, 3.2492, 1.6545],
          [2.0207, 1.6958, 1.8471, 0.8338, 3.0506, 3.1423, 3.2835, 1.3767],
          [1.9030, 1.5254, 1.4021, 2.5892, 2.5467, 1.6599, 1.7575, 1.1418],
          [2.1492, 1.5503, 1.4249, 1.8803, 1.7536, 2.6992, 1.2558, 2.2438],
          [2.6675, 1.0331, 1.1781, 0.9944, 2.0451, 1.7235, 1.4303, 2.0411],
          [1.2586, 1.7807, 2.4085, 2.0107, 2.3379, 1.0800, 1.9881, 1.4275],
          [1.8143, 2.8771, 1.0929, 1.7023, 2.1186, 2.1242, 1.4403, 1.0744]],

         [[1.6399, 1.8884, 0.8022, 1.3953, 1.4934, 2.7523, 1.5673, 0.9981],
          [0.5793, 2.0730, 1.3050, 1.3257, 1.2001, 1.6155, 1.8762, 1.7314],
          [1.0106, 2.4755, 1.1288, 1.7837, 2.3973, 1.2521, 1.4686, 2.0514],
          [1.1400, 2.2882, 1.8141, 1.1265, 0.8046, 2.2316, 0.5494, 1.8949],
          [1.8246, 2.2268, 2.5240, 1.5624, 2.8340, 2.0574, 1.7611, 1.0739],
          

In [65]:
def roipool(x, boxes, output_size=(8,8)):
    
    roi_start_h = int(boxes[0][1])
    roi_start_w = int(boxes[0][2])
    roi_end_h = int(boxes[0][3])
    roi_end_w = int(boxes[0][4])
    roi_width = (roi_end_w - roi_start_w + 1)
    roi_height = (roi_end_h - roi_start_h + 1)

    bin_size_w = roi_width / 8
    bin_size_h = roi_height / 8
    
    self_result = []
    for k in range(x.shape[1]):
        temp = []
        for j in range(8):
            sub_res = []
            for i in range(8):
                sub_res.append(x[..., int(0+bin_size_h*(j)):math.ceil(0+bin_size_h*(j+1)),
                                     int(0+bin_size_w*(i)):math.ceil(0+bin_size_w*(i+1))][0][k].max())
            temp.append(sub_res)
        self_result.append(temp)
    res=torch.Tensor(self_result)
    return res

In [66]:
output_7_ = roipool(Input, box, output_size=(8,8))
output_7_

tensor([[[2.1981, 1.9790, 1.6071, 2.0625, 1.0465, 0.8380, 2.3753, 1.8966],
         [1.2296, 1.9685, 2.0244, 2.4132, 3.0291, 1.6265, 3.2492, 1.6545],
         [2.0207, 1.6958, 1.8471, 0.8338, 3.0506, 3.1423, 3.2835, 1.3767],
         [1.9030, 1.5254, 1.4021, 2.5892, 2.5467, 1.6599, 1.7575, 1.1418],
         [2.1492, 1.5503, 1.4249, 1.8803, 1.7536, 2.6992, 1.2558, 2.2438],
         [2.6675, 1.0331, 1.1781, 0.9944, 2.0451, 1.7235, 1.4303, 2.0411],
         [1.2586, 1.7807, 2.4085, 2.0107, 2.3379, 1.0800, 1.9881, 1.4275],
         [1.8143, 2.8771, 1.0929, 1.7023, 2.1186, 2.1242, 1.4403, 1.0744]],

        [[1.6399, 1.8884, 0.8022, 1.3953, 1.4934, 2.7523, 1.5673, 0.9981],
         [0.5793, 2.0730, 1.3050, 1.3257, 1.2001, 1.6155, 1.8762, 1.7314],
         [1.0106, 2.4755, 1.1288, 1.7837, 2.3973, 1.2521, 1.4686, 2.0514],
         [1.1400, 2.2882, 1.8141, 1.1265, 0.8046, 2.2316, 0.5494, 1.8949],
         [1.8246, 2.2268, 2.5240, 1.5624, 2.8340, 2.0574, 1.7611, 1.0739],
         [2.0119, 1.625

In [67]:
error_7 = torch.nn.functional.mse_loss(output_7,output_7_)
error_7

<ipython-input-67-eb177f28b4f7>:1: UserWarning: Using a target size (torch.Size([3, 8, 8])) that is different to the input size (torch.Size([1, 3, 8, 8])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  error_7 = torch.nn.functional.mse_loss(output_7,output_7_)


tensor(0.)

## Function 8: torch.nn.functional.batch_norm

In [27]:
running_mean = torch.zeros(3)+1
running_var = torch.ones(3)*2
output_8 = torch.nn.functional.batch_norm(Input, running_mean, running_var, weight=None, bias=None, training=False, momentum=0.1, eps=1e-05)
output_8

tensor([[[[ 8.4715e-01, -1.0356e+00, -8.1788e-01,  ..., -4.5378e-01,
           -3.4808e-01, -2.4996e-01],
          [-1.1880e+00, -1.7242e+00, -1.0394e+00,  ..., -1.8123e+00,
           -8.8706e-01, -9.3564e-01],
          [ 2.5101e-01, -6.1962e-01, -1.0490e+00,  ..., -1.4341e+00,
           -2.2515e+00, -7.8734e-01],
          ...,
          [-9.4771e-01, -3.6150e-01, -8.5304e-01,  ..., -1.1061e+00,
           -2.3564e-01, -5.0672e-01],
          [ 5.7579e-01, -4.4478e-02, -1.0353e+00,  ..., -9.7996e-01,
           -3.2826e-01,  5.2621e-02],
          [-1.4219e+00, -7.9475e-01,  1.2240e-02,  ..., -1.0008e+00,
           -1.4902e+00, -1.2112e+00]],

         [[-1.0834e+00, -5.4995e-01,  4.5247e-01,  ..., -2.2382e+00,
           -1.8470e+00, -2.0792e+00],
          [-2.8049e-01, -5.6402e-01, -5.5360e-01,  ..., -1.3666e-03,
           -2.9825e-01, -7.0809e-01],
          [-1.2865e+00,  1.1202e-01, -1.3250e+00,  ..., -3.0829e-01,
           -1.0649e+00, -5.0279e-01],
          ...,
     

In [28]:
def batchnorm(input, running_mean, running_var, momentum=0.1, eps=1e-05):
    mean = running_mean
    var = running_var
    mean, var = mean[:,None,None],var[:,None,None]
    
    return (input-mean) / torch.sqrt(var+eps)

In [29]:
output_8_ = batchnorm(Input, running_mean, running_var, momentum=0.1, eps=1e-05)
output_8_

tensor([[[[ 8.4715e-01, -1.0356e+00, -8.1788e-01,  ..., -4.5378e-01,
           -3.4808e-01, -2.4996e-01],
          [-1.1880e+00, -1.7242e+00, -1.0394e+00,  ..., -1.8123e+00,
           -8.8706e-01, -9.3564e-01],
          [ 2.5101e-01, -6.1962e-01, -1.0490e+00,  ..., -1.4341e+00,
           -2.2515e+00, -7.8734e-01],
          ...,
          [-9.4771e-01, -3.6150e-01, -8.5304e-01,  ..., -1.1061e+00,
           -2.3564e-01, -5.0672e-01],
          [ 5.7579e-01, -4.4478e-02, -1.0353e+00,  ..., -9.7996e-01,
           -3.2826e-01,  5.2621e-02],
          [-1.4219e+00, -7.9475e-01,  1.2240e-02,  ..., -1.0008e+00,
           -1.4902e+00, -1.2112e+00]],

         [[-1.0834e+00, -5.4995e-01,  4.5247e-01,  ..., -2.2382e+00,
           -1.8470e+00, -2.0792e+00],
          [-2.8049e-01, -5.6402e-01, -5.5360e-01,  ..., -1.3666e-03,
           -2.9825e-01, -7.0809e-01],
          [-1.2865e+00,  1.1202e-01, -1.3250e+00,  ..., -3.0829e-01,
           -1.0649e+00, -5.0279e-01],
          ...,
     

In [73]:
error_8 = torch.nn.functional.mse_loss(output_8,output_8_)
error_8

tensor(3.8506e-15)

## Function 9: torch.nn.functional.cross_entropy

In [30]:
target = torch.randint(0,3, (1,32,32), dtype=torch.int64)
target

tensor([[[1, 0, 1,  ..., 1, 2, 1],
         [1, 1, 1,  ..., 1, 1, 2],
         [0, 2, 1,  ..., 1, 2, 0],
         ...,
         [0, 2, 1,  ..., 0, 0, 2],
         [2, 2, 0,  ..., 1, 2, 1],
         [1, 0, 1,  ..., 0, 2, 0]]])

In [31]:
output_9 = torch.nn.functional.cross_entropy(Input, target,weight=None, size_average=None, ignore_index=-100, reduce=None, reduction='mean')
output_9

tensor(1.3646)

In [32]:
def softmax(x):
    maxes = torch.max(x, 1, keepdim=True)[0]
    x_exp = torch.exp(x-maxes)
    x_exp_sum = torch.sum(x_exp, 1, keepdim=True)

    return x_exp/x_exp_sum

In [33]:
Input_softmax = np.array(softmax(Input)[0])
target = np.array(target)
loss = 0.0
for b in range(target.shape[0]):
    for i in range(target.shape[1]):
        for j in range(target.shape[2]):
            loss -= np.log(Input_softmax[target[b][i][j]][i][j])/1024
print(torch.tensor(loss))  

tensor(1.3646, dtype=torch.float64)


## Function 10: torch.nn.functional.mse_loss

In [34]:
target = torch.randn(1,3,32,32)
output_10 = torch.nn.functional.mse_loss(Input, target, size_average=None, reduce=None, reduction='mean')
output_10

tensor(2.0336)

In [35]:
def mse(inp,target):
    MSE = np.square(np.subtract(inp,target)).mean()
    return MSE

In [36]:
output_10_ = mse(Input, target)
output_10_

tensor(2.0336)