# Assignment 3_LI XINYA

### Import the libraries

In [1]:
import pandas as pd
import numpy as np
import torch
import torchvision
import math

### Define the Input:

In [2]:
# 32x32 pixels, 3 channels
Input = torch.randn(1,3,32,32)
Input

tensor([[[[-0.7558,  2.0387,  1.0288,  ..., -2.0488, -1.4186,  1.0614],
          [-0.7613,  0.1861,  1.3850,  ...,  0.2777, -0.8501,  1.0003],
          [-0.7041, -2.2867,  0.9484,  ..., -1.0959,  1.0530, -0.1374],
          ...,
          [ 0.4801,  1.0331, -1.1497,  ..., -0.5086, -1.5611,  1.0551],
          [ 0.7426,  0.5774,  1.7801,  ..., -0.7559, -0.8958, -0.9228],
          [ 0.0233,  0.6899,  1.1532,  ...,  0.8242,  2.3834, -0.7420]],

         [[-1.3799, -0.6431, -1.2076,  ...,  0.4010,  0.4011, -0.3269],
          [ 0.4548,  1.6678,  1.7985,  ..., -0.7643,  1.1700,  0.5061],
          [ 0.5173, -0.1261,  0.0234,  ...,  1.3064,  0.3255, -0.0399],
          ...,
          [-0.6854, -0.6673,  0.1265,  ...,  0.7148,  0.1541,  1.3416],
          [ 1.1086,  1.2910,  0.9547,  ...,  2.0975, -0.1046,  1.0120],
          [ 2.4014,  0.3279, -0.2108,  ..., -0.0281,  0.9178, -0.6500]],

         [[-0.7708,  1.6814,  0.7419,  ..., -0.6735,  0.5220,  0.3278],
          [ 0.2696,  0.6320, -

## Function 1: torch.nn.MaxPool2d

In [3]:
# using pytorch
layer_1 = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, return_indices=False, ceil_mode=False)
output_1 = layer_1(Input)
output_1

tensor([[[[ 2.0387,  2.0387,  1.3850,  ...,  1.4211,  0.2777,  1.0614],
          [ 0.1861,  1.3850,  1.3850,  ...,  1.4211,  1.0530,  1.0530],
          [ 0.6221,  0.9484,  0.9484,  ..., -0.2366,  1.0530,  1.0530],
          ...,
          [ 1.0331,  1.0331,  0.7629,  ...,  0.2477, -0.0308,  1.0551],
          [ 1.0331,  1.7801,  1.7801,  ...,  0.2477, -0.5086,  1.0551],
          [ 0.7426,  1.7801,  1.7801,  ...,  0.8242,  2.3834,  2.3834]],

         [[ 1.6678,  1.7985,  1.7985,  ...,  0.4010,  1.1700,  1.1700],
          [ 1.6678,  1.7985,  1.7985,  ...,  1.3064,  1.3064,  1.1700],
          [ 0.8280,  0.6004,  1.4068,  ...,  1.3064,  2.0968,  2.0968],
          ...,
          [ 0.5622,  0.5622,  1.5691,  ...,  1.1794,  0.7148,  1.3416],
          [ 1.2910,  1.2910,  1.6494,  ...,  2.0975,  2.0975,  1.3416],
          [ 2.4014,  1.2910,  2.7753,  ...,  2.0975,  2.0975,  1.0120]],

         [[ 1.6814,  1.6814,  0.7419,  ...,  1.3578,  0.5220,  0.5220],
          [ 1.9123,  1.2722,  

In [4]:
def max_pooling(x, pool_param):
    out = None
    N, C, H, W = x.shape
    HH, WW = pool_param['pool_height'], pool_param['pool_width']
    stride = pool_param['stride']
  
    H_out = 1 + (H - HH) // stride
    W_out = 1 + (W - WW) // stride
  
    out = torch.zeros((N, C, H_out, W_out), device=x.device, dtype=x.dtype)
    for img in range(N):
        for channel in range(C):
            for i in range(H_out):
                for j in range(W_out):
                    out[img, channel, i, j] = torch.max(x[img, channel, i*stride:i*stride+HH, j*stride:j*stride+WW])
    cache = (x, pool_param)
    return out

In [5]:
pool_param = {'pool_width': 2, 'pool_height': 2, 'stride': 1}
output_1_ = max_pooling(Input,pool_param)
output_1_

tensor([[[[ 2.0387,  2.0387,  1.3850,  ...,  1.4211,  0.2777,  1.0614],
          [ 0.1861,  1.3850,  1.3850,  ...,  1.4211,  1.0530,  1.0530],
          [ 0.6221,  0.9484,  0.9484,  ..., -0.2366,  1.0530,  1.0530],
          ...,
          [ 1.0331,  1.0331,  0.7629,  ...,  0.2477, -0.0308,  1.0551],
          [ 1.0331,  1.7801,  1.7801,  ...,  0.2477, -0.5086,  1.0551],
          [ 0.7426,  1.7801,  1.7801,  ...,  0.8242,  2.3834,  2.3834]],

         [[ 1.6678,  1.7985,  1.7985,  ...,  0.4010,  1.1700,  1.1700],
          [ 1.6678,  1.7985,  1.7985,  ...,  1.3064,  1.3064,  1.1700],
          [ 0.8280,  0.6004,  1.4068,  ...,  1.3064,  2.0968,  2.0968],
          ...,
          [ 0.5622,  0.5622,  1.5691,  ...,  1.1794,  0.7148,  1.3416],
          [ 1.2910,  1.2910,  1.6494,  ...,  2.0975,  2.0975,  1.3416],
          [ 2.4014,  1.2910,  2.7753,  ...,  2.0975,  2.0975,  1.0120]],

         [[ 1.6814,  1.6814,  0.7419,  ...,  1.3578,  0.5220,  0.5220],
          [ 1.9123,  1.2722,  

In [6]:
# check the difference
print(torch.allclose(output_1, output_1_))

True


## Function 2: torch.nn.AvgPool2d

In [7]:
# using pytorch
layer_2 = torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0,ceil_mode=False, count_include_pad=True,divisor_override=None)
output_2 = layer_2(Input)
output_2

tensor([[[[ 0.1769,  1.1597,  0.6873,  ..., -0.0635, -1.0100, -0.0517],
          [-0.8915,  0.0582,  0.8878,  ...,  0.0916, -0.1538,  0.2665],
          [-0.7355, -0.7566, -0.3368,  ..., -1.1892, -0.5271,  0.2752],
          ...,
          [ 0.1980,  0.0567, -0.5479,  ..., -0.4023, -0.8259, -0.6262],
          [ 0.7083,  0.5602,  0.1020,  ..., -0.2276, -0.9303, -0.5811],
          [ 0.5083,  1.0501,  0.6166,  ..., -0.4036,  0.3890, -0.0443]],

         [[ 0.0249,  0.4039, -0.0413,  ..., -0.2404,  0.3019,  0.4376],
          [ 0.6285,  0.8409,  0.0735,  ...,  0.1341,  0.5094,  0.4904],
          [ 0.1817,  0.0013,  0.2620,  ...,  0.4708,  1.1975,  0.9331],
          ...,
          [-0.6257, -0.2945,  0.3681,  ...,  0.1992, -0.2980,  0.1228],
          [ 0.2617,  0.4262,  0.9267,  ...,  0.7211,  0.7154,  0.6008],
          [ 1.2822,  0.5907,  1.2921,  ...,  0.1958,  0.7206,  0.2938]],

         [[ 0.4531,  0.6477, -0.4955,  ...,  0.3269, -0.0879, -0.0134],
          [ 1.0215,  0.4432, -

In [8]:
def avg_pooling(x, pool_param):
    out = None
    N, C, H, W = x.shape
    HH, WW = pool_param['pool_height'], pool_param['pool_width']
    stride = pool_param['stride']
  
    H_out = 1 + (H - HH) // stride
    W_out = 1 + (W - WW) // stride
  
    out = torch.zeros((N, C, H_out, W_out), device=x.device, dtype=x.dtype)
    for img in range(N):
        for channel in range(C):
            for i in range(H_out):
                for j in range(W_out):
                    out[img, channel, i, j] = torch.mean(x[img, channel, i*stride:i*stride+HH, j*stride:j*stride+WW])
    return out

In [9]:
pool_param = {'pool_width': 2, 'pool_height': 2, 'stride': 1}
output_2_ = avg_pooling(Input,pool_param)
output_2_

tensor([[[[ 0.1769,  1.1597,  0.6873,  ..., -0.0635, -1.0100, -0.0517],
          [-0.8915,  0.0582,  0.8878,  ...,  0.0916, -0.1538,  0.2665],
          [-0.7355, -0.7566, -0.3368,  ..., -1.1892, -0.5271,  0.2752],
          ...,
          [ 0.1980,  0.0567, -0.5479,  ..., -0.4023, -0.8259, -0.6262],
          [ 0.7083,  0.5602,  0.1020,  ..., -0.2276, -0.9303, -0.5811],
          [ 0.5083,  1.0501,  0.6166,  ..., -0.4036,  0.3890, -0.0443]],

         [[ 0.0249,  0.4039, -0.0413,  ..., -0.2404,  0.3019,  0.4376],
          [ 0.6285,  0.8409,  0.0735,  ...,  0.1341,  0.5094,  0.4904],
          [ 0.1817,  0.0013,  0.2620,  ...,  0.4708,  1.1975,  0.9331],
          ...,
          [-0.6257, -0.2945,  0.3681,  ...,  0.1992, -0.2980,  0.1228],
          [ 0.2617,  0.4262,  0.9267,  ...,  0.7211,  0.7154,  0.6008],
          [ 1.2822,  0.5907,  1.2921,  ...,  0.1958,  0.7206,  0.2938]],

         [[ 0.4531,  0.6477, -0.4955,  ...,  0.3269, -0.0879, -0.0134],
          [ 1.0215,  0.4432, -

In [10]:
# check the difference
print(torch.allclose(output_2, output_2_))

False


## Function 3: torch.nn.Conv2d
## stride=1

In [11]:
layer_3 = torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=3, stride=1, padding=0, dilation=1, groups=1,bias=True, padding_mode="zeros")
output_3_1 = layer_3(Input)
output_3_1                      

tensor([[[[-3.2976e-02,  1.3121e-01,  2.0484e-01,  ...,  7.4906e-01,
            1.3600e+00, -8.6983e-01],
          [-3.7839e-01,  5.9798e-01,  6.5141e-01,  ..., -3.0311e-01,
            9.4763e-01,  5.6681e-01],
          [ 2.5600e-01, -3.1248e-01,  6.2639e-01,  ...,  3.7697e-01,
           -1.1824e+00, -2.3969e-01],
          ...,
          [-5.3720e-01,  4.8039e-01, -4.0414e-01,  ..., -1.3243e-01,
            8.1123e-01,  2.4057e-02],
          [-1.1449e-01, -1.3489e-01, -4.6111e-01,  ..., -1.2845e-01,
            1.0085e+00, -3.3705e-01],
          [-4.6251e-01,  6.8161e-01, -1.5352e-01,  ...,  6.4639e-01,
            5.2642e-01,  3.3931e-01]],

         [[ 5.3442e-01,  1.7813e+00,  2.1973e-01,  ...,  9.5377e-01,
            1.8852e-01, -4.3269e-01],
          [-6.2358e-02, -1.2308e-01,  1.4968e-01,  ...,  8.0590e-01,
            7.4828e-01, -6.2598e-01],
          [ 2.6239e-01,  5.4602e-01,  3.5679e-01,  ...,  1.1018e-02,
           -9.7256e-01, -3.3239e-01],
          ...,
     

In [12]:
def conv2d(x, w, b, conv_param):
    out = None
    padding = torch.nn.functional.pad
    pad = conv_param['pad']
    stride = conv_param['stride']
    N, C, H, W = x.shape
    F, _, HH, WW = w.shape
  
    H_out = 1 + (H + 2 * pad - HH) // stride
    W_out = 1 + (W + 2 * pad - WW) // stride
    out = torch.zeros((N, F, H_out, W_out), device = x.device, dtype= x.dtype)
  
    x_pad = padding(x, (pad, pad, pad, pad), mode='constant', value=0) 
    for image in range(N): # each image
        for flr in range(F): # for each filter
            for i in range(H_out): # row
                for j in range(W_out): # column
                    out[image, flr, i, j] = torch.sum(x_pad[image, : , i*stride:i*stride+HH, j*stride:j*stride+WW] * w[flr, :, :, :]) + b[flr]
    return out

In [13]:
conv_param = {'stride': 1, 'pad': 0}
output_3_1_ = conv2d(Input, layer_3.weight, layer_3.bias, conv_param)
output_3_1_

tensor([[[[-3.2976e-02,  1.3121e-01,  2.0484e-01,  ...,  7.4906e-01,
            1.3600e+00, -8.6983e-01],
          [-3.7839e-01,  5.9798e-01,  6.5141e-01,  ..., -3.0311e-01,
            9.4763e-01,  5.6681e-01],
          [ 2.5600e-01, -3.1248e-01,  6.2639e-01,  ...,  3.7697e-01,
           -1.1824e+00, -2.3969e-01],
          ...,
          [-5.3720e-01,  4.8038e-01, -4.0414e-01,  ..., -1.3243e-01,
            8.1123e-01,  2.4057e-02],
          [-1.1449e-01, -1.3489e-01, -4.6111e-01,  ..., -1.2845e-01,
            1.0085e+00, -3.3705e-01],
          [-4.6251e-01,  6.8161e-01, -1.5352e-01,  ...,  6.4639e-01,
            5.2642e-01,  3.3931e-01]],

         [[ 5.3442e-01,  1.7813e+00,  2.1973e-01,  ...,  9.5377e-01,
            1.8852e-01, -4.3269e-01],
          [-6.2358e-02, -1.2308e-01,  1.4968e-01,  ...,  8.0590e-01,
            7.4828e-01, -6.2598e-01],
          [ 2.6239e-01,  5.4602e-01,  3.5679e-01,  ...,  1.1018e-02,
           -9.7256e-01, -3.3239e-01],
          ...,
     

In [14]:
error_3_1 = torch.nn.functional.mse_loss(output_3_1,output_3_1_)
error_3_1

tensor(5.1135e-15, grad_fn=<MseLossBackward>)

## stride=2

In [15]:
layer_3_ = torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=5, stride=2, padding=0, dilation=1, groups=1,bias=True, padding_mode="zeros")
output_3_2 = layer_3_(Input)
output_3_2 

tensor([[[[-0.5100, -0.1946, -0.6698,  ..., -0.4874,  0.5552, -0.0799],
          [ 0.4761,  0.2524,  0.6928,  ..., -1.1386,  0.0592, -0.1814],
          [ 1.2491, -0.0214,  0.6534,  ..., -0.1810,  0.2880, -0.2452],
          ...,
          [ 0.2355,  0.9615, -0.7270,  ..., -0.1700,  0.3467, -1.1097],
          [-0.2335,  0.2703, -0.3161,  ..., -0.7719,  1.1219, -1.1921],
          [ 0.0079, -0.9552,  0.4628,  ...,  0.5306, -0.4134, -1.2064]],

         [[-0.3835,  0.7918,  1.2052,  ...,  0.5275, -0.6825, -0.2297],
          [ 0.5994, -0.3845,  0.6312,  ..., -0.1070,  0.2326,  0.5235],
          [-2.0125, -0.3935, -0.0764,  ..., -0.3373, -0.3728, -0.8195],
          ...,
          [-0.0974, -0.6719, -0.2863,  ..., -0.4970, -0.7085,  0.1284],
          [-0.2445, -0.2734,  0.1990,  ..., -0.8391,  0.3100,  0.0656],
          [-0.1633,  0.7418, -0.8226,  ...,  1.1023,  0.6529,  0.2457]],

         [[-0.1350, -0.3956, -0.0434,  ..., -0.1134, -0.4243, -0.4172],
          [ 0.0398, -0.1222,  

In [16]:
conv_param = {'stride': 2, 'pad': 0}
output_3_2_ = conv2d(Input, layer_3_.weight, layer_3_.bias, conv_param)
output_3_2_

tensor([[[[-0.5100, -0.1946, -0.6698,  ..., -0.4874,  0.5552, -0.0799],
          [ 0.4761,  0.2524,  0.6928,  ..., -1.1386,  0.0592, -0.1814],
          [ 1.2491, -0.0214,  0.6534,  ..., -0.1810,  0.2880, -0.2452],
          ...,
          [ 0.2355,  0.9615, -0.7270,  ..., -0.1700,  0.3467, -1.1097],
          [-0.2335,  0.2703, -0.3161,  ..., -0.7719,  1.1219, -1.1921],
          [ 0.0079, -0.9552,  0.4628,  ...,  0.5306, -0.4134, -1.2064]],

         [[-0.3835,  0.7918,  1.2052,  ...,  0.5275, -0.6825, -0.2297],
          [ 0.5994, -0.3845,  0.6312,  ..., -0.1070,  0.2326,  0.5235],
          [-2.0125, -0.3935, -0.0764,  ..., -0.3373, -0.3728, -0.8195],
          ...,
          [-0.0974, -0.6719, -0.2863,  ..., -0.4970, -0.7085,  0.1284],
          [-0.2445, -0.2734,  0.1990,  ..., -0.8391,  0.3100,  0.0656],
          [-0.1633,  0.7418, -0.8226,  ...,  1.1023,  0.6529,  0.2457]],

         [[-0.1350, -0.3956, -0.0434,  ..., -0.1134, -0.4243, -0.4172],
          [ 0.0398, -0.1222,  

In [17]:
error_3_2 = torch.nn.functional.mse_loss(output_3_2,output_3_2_)
error_3_2

tensor(1.0054e-14, grad_fn=<MseLossBackward>)

## Function 4: torch.nn.ConvTranspose2d

In [18]:
layer_4 = torch.nn.ConvTranspose2d(in_channels=3, out_channels=4,kernel_size=3, stride=1, padding=0, output_padding=0,groups=1, bias=True, dilation=1, padding_mode='zeros')
output_4 = layer_4(Input)
output_4

tensor([[[[ 1.2450e-01, -1.0695e-01,  1.5536e-01,  ...,  7.5601e-02,
            1.2034e-01, -2.0071e-01],
          [-3.6263e-01, -1.9436e-01, -3.8466e-01,  ..., -1.4307e-01,
            2.9151e-02, -4.4915e-01],
          [ 1.0462e-01,  9.0877e-01,  4.3371e-01,  ..., -4.9564e-01,
           -5.3206e-01, -1.4935e-01],
          ...,
          [-1.3347e-01, -2.2189e-01, -5.5524e-01,  ...,  5.0240e-01,
           -2.9189e-01,  4.0951e-01],
          [ 3.3466e-01, -1.2458e-01,  3.0278e-01,  ..., -7.7696e-02,
           -3.4683e-01, -9.3250e-02],
          [-1.1291e-01, -4.1232e-02, -5.2186e-02,  ..., -2.2024e-01,
            2.3397e-01, -2.5624e-01]],

         [[-7.7326e-02,  3.2081e-01,  5.4866e-01,  ...,  3.7670e-01,
            3.5298e-01,  6.4336e-02],
          [ 3.2276e-02,  3.0177e-01,  7.3247e-01,  ...,  6.4463e-02,
            4.8906e-01, -1.0739e-01],
          [ 1.8158e-01, -3.9331e-01,  5.7894e-02,  ..., -3.2371e-03,
            5.2480e-02, -2.8471e-02],
          ...,
     

In [19]:
def trans(x, weight, bias, channel):
    h = weight.shape[2]
    w = weight.shape[3]
    out = torch.zeros((1, x.shape[1] + h - 1, x.shape[2] + w - 1))
    for k in range(x.shape[0]):
        for i in range(x.shape[1]):
            for j in range(x.shape[2]):
                out[0,i:i + h, j:j + w] += x[k, i, j] * weight[k][channel]
    out += bias[channel]
    return out
def trans_conv(x, weight, bias, out_channel):
    result = []
    
    for i in range(out_channel):
        out = trans(x, weight, bias, i)
        result.append(out[0])
    return torch.stack(result,dim = 0)

In [20]:
output_4_ = trans_conv(Input[0], layer_4.weight, layer_4.bias, layer_4.out_channels)
output_4_

tensor([[[ 1.2450e-01, -1.0695e-01,  1.5536e-01,  ...,  7.5601e-02,
           1.2034e-01, -2.0071e-01],
         [-3.6263e-01, -1.9436e-01, -3.8466e-01,  ..., -1.4307e-01,
           2.9151e-02, -4.4915e-01],
         [ 1.0462e-01,  9.0877e-01,  4.3371e-01,  ..., -4.9564e-01,
          -5.3206e-01, -1.4935e-01],
         ...,
         [-1.3347e-01, -2.2189e-01, -5.5524e-01,  ...,  5.0240e-01,
          -2.9189e-01,  4.0951e-01],
         [ 3.3466e-01, -1.2458e-01,  3.0278e-01,  ..., -7.7696e-02,
          -3.4683e-01, -9.3250e-02],
         [-1.1291e-01, -4.1232e-02, -5.2186e-02,  ..., -2.2024e-01,
           2.3397e-01, -2.5624e-01]],

        [[-7.7326e-02,  3.2081e-01,  5.4866e-01,  ...,  3.7670e-01,
           3.5298e-01,  6.4336e-02],
         [ 3.2276e-02,  3.0177e-01,  7.3247e-01,  ...,  6.4463e-02,
           4.8906e-01, -1.0739e-01],
         [ 1.8158e-01, -3.9331e-01,  5.7895e-02,  ..., -3.2371e-03,
           5.2480e-02, -2.8471e-02],
         ...,
         [ 1.2571e-01,  5

In [21]:
error_4 = torch.nn.functional.mse_loss(output_4[0],output_4_)
error_4

tensor(3.0256e-15, grad_fn=<MseLossBackward>)

## Function 5: torch.flatten

In [22]:
output_5 = torch.flatten(Input, start_dim=0, end_dim=-1)
output_5

tensor([-0.7558,  2.0387,  1.0288,  ..., -0.4450,  0.8886,  0.0909])

In [23]:
def Flatten(inp):
    flatten_list = []
    for i in inp:
        for j in i:
            for h in j:  
                for w in h:
                    flatten_list.append(w)
    return torch.tensor(np.array(flatten_list))

In [24]:
output_5_ = Flatten(Input)
output_5_

tensor([-0.7558,  2.0387,  1.0288,  ..., -0.4450,  0.8886,  0.0909])

In [25]:
error_5 = torch.nn.functional.mse_loss(output_5,output_5_)
error_5

tensor(0.)

## Function 6: torch.sigmoid

In [26]:
output_6 = torch.sigmoid(Input, out=None)
output_6

tensor([[[[0.3195, 0.8848, 0.7367,  ..., 0.1142, 0.1949, 0.7430],
          [0.3184, 0.5464, 0.7998,  ..., 0.5690, 0.2994, 0.7311],
          [0.3309, 0.0922, 0.7208,  ..., 0.2505, 0.7414, 0.4657],
          ...,
          [0.6178, 0.7375, 0.2405,  ..., 0.3755, 0.1735, 0.7418],
          [0.6776, 0.6405, 0.8557,  ..., 0.3195, 0.2899, 0.2844],
          [0.5058, 0.6659, 0.7601,  ..., 0.6951, 0.9155, 0.3226]],

         [[0.2010, 0.3445, 0.2301,  ..., 0.5989, 0.5989, 0.4190],
          [0.6118, 0.8413, 0.8580,  ..., 0.3177, 0.7632, 0.6239],
          [0.6265, 0.4685, 0.5058,  ..., 0.7869, 0.5807, 0.4900],
          ...,
          [0.3351, 0.3391, 0.5316,  ..., 0.6715, 0.5385, 0.7928],
          [0.7519, 0.7843, 0.7221,  ..., 0.8907, 0.4739, 0.7334],
          [0.9169, 0.5813, 0.4475,  ..., 0.4930, 0.7146, 0.3430]],

         [[0.3163, 0.8431, 0.6774,  ..., 0.3377, 0.6276, 0.5812],
          [0.5670, 0.6529, 0.3859,  ..., 0.5680, 0.3836, 0.3943],
          [0.8713, 0.7811, 0.5826,  ..., 0

In [27]:
def Sigmoid (inp):
    output = 1.0 / (1.0 + np.exp(-inp))
    return output
    
output_6_ = Sigmoid (Input)
output_6_

tensor([[[[0.3195, 0.8848, 0.7367,  ..., 0.1142, 0.1949, 0.7430],
          [0.3184, 0.5464, 0.7998,  ..., 0.5690, 0.2994, 0.7311],
          [0.3309, 0.0922, 0.7208,  ..., 0.2505, 0.7414, 0.4657],
          ...,
          [0.6178, 0.7375, 0.2405,  ..., 0.3755, 0.1735, 0.7418],
          [0.6776, 0.6405, 0.8557,  ..., 0.3195, 0.2899, 0.2844],
          [0.5058, 0.6659, 0.7601,  ..., 0.6951, 0.9155, 0.3226]],

         [[0.2010, 0.3445, 0.2301,  ..., 0.5989, 0.5989, 0.4190],
          [0.6118, 0.8413, 0.8580,  ..., 0.3177, 0.7632, 0.6239],
          [0.6265, 0.4685, 0.5058,  ..., 0.7869, 0.5807, 0.4900],
          ...,
          [0.3351, 0.3391, 0.5316,  ..., 0.6715, 0.5385, 0.7928],
          [0.7519, 0.7843, 0.7221,  ..., 0.8907, 0.4739, 0.7334],
          [0.9169, 0.5813, 0.4475,  ..., 0.4930, 0.7146, 0.3430]],

         [[0.3163, 0.8431, 0.6774,  ..., 0.3377, 0.6276, 0.5812],
          [0.5670, 0.6529, 0.3859,  ..., 0.5680, 0.3836, 0.3943],
          [0.8713, 0.7811, 0.5826,  ..., 0

In [28]:
error_6 = torch.nn.functional.mse_loss(output_6,output_6_)
error_6

tensor(0.)

## Function 7: torchvision.ops.roi_pool

In [29]:
box = torch.tensor([[0,0,0,31,31]]).float()
output_7 = torchvision.ops.roi_pool(Input, box,output_size=(8,8))
output_7

tensor([[[[2.0387, 2.5075, 0.8858, 1.5336, 3.0051, 1.1509, 1.2784, 1.4211],
          [1.7025, 2.1234, 1.9850, 2.3964, 2.5356, 2.2008, 0.9719, 1.4893],
          [2.5831, 1.3468, 2.2122, 1.5671, 1.1527, 2.1048, 0.3130, 1.6683],
          [2.2101, 1.9599, 2.4244, 1.8702, 1.7917, 1.5855, 1.6899, 2.0609],
          [1.2848, 2.4111, 1.6422, 1.6720, 2.4414, 1.0805, 1.2674, 2.0879],
          [2.2280, 2.1057, 1.8990, 1.0819, 1.0045, 2.7609, 1.4252, 1.2953],
          [0.9011, 1.2752, 2.4465, 1.7873, 2.7165, 1.4459, 2.1348, 2.3154],
          [1.7801, 1.3175, 1.9581, 0.9011, 2.0920, 2.4126, 1.7110, 2.3834]],

         [[1.7985, 1.6265, 3.0189, 1.2877, 3.2693, 1.1084, 2.1343, 2.0968],
          [2.1883, 1.9161, 0.9040, 1.9849, 1.9526, 1.8139, 1.3221, 1.7757],
          [1.9679, 0.8414, 1.4654, 0.7867, 2.2469, 1.3771, 1.6252, 2.3525],
          [1.0176, 1.6061, 1.6777, 2.4566, 1.4945, 1.0139, 1.3958, 3.2499],
          [1.6652, 2.2066, 2.0437, 1.7641, 1.8917, 3.1331, 1.6696, 2.2509],
          

In [46]:
def roipool(x, box, output_size=(8,8)):
    
    roi_h_1 = int(box[0][1])
    roi_w_1 = int(box[0][2])
    roi_h_2 = int(box[0][3])
    roi_w_2 = int(box[0][4])
    roi_width = (roi_w_2 - roi_w_1 + 1)
    roi_height = (roi_h_2 - roi_h_1 + 1)

    bin_size_w = roi_width / 8
    bin_size_h = roi_height / 8
    
    result = []
    for k in range(x.shape[1]):
        temp = []
        for j in range(8):
            sub_res = []
            for i in range(8):
                sub_res.append(x[..., int(0+bin_size_h*(j)):math.ceil(0+bin_size_h*(j+1)),
                                     int(0+bin_size_w*(i)):math.ceil(0+bin_size_w*(i+1))][0][k].max())
            temp.append(sub_res)
        result.append(temp)
    result=torch.Tensor(result)
    return result

In [31]:
output_7_ = roipool(Input, box, output_size=(8,8))
output_7_

tensor([[[2.0387, 2.5075, 0.8858, 1.5336, 3.0051, 1.1509, 1.2784, 1.4211],
         [1.7025, 2.1234, 1.9850, 2.3964, 2.5356, 2.2008, 0.9719, 1.4893],
         [2.5831, 1.3468, 2.2122, 1.5671, 1.1527, 2.1048, 0.3130, 1.6683],
         [2.2101, 1.9599, 2.4244, 1.8702, 1.7917, 1.5855, 1.6899, 2.0609],
         [1.2848, 2.4111, 1.6422, 1.6720, 2.4414, 1.0805, 1.2674, 2.0879],
         [2.2280, 2.1057, 1.8990, 1.0819, 1.0045, 2.7609, 1.4252, 1.2953],
         [0.9011, 1.2752, 2.4465, 1.7873, 2.7165, 1.4459, 2.1348, 2.3154],
         [1.7801, 1.3175, 1.9581, 0.9011, 2.0920, 2.4126, 1.7110, 2.3834]],

        [[1.7985, 1.6265, 3.0189, 1.2877, 3.2693, 1.1084, 2.1343, 2.0968],
         [2.1883, 1.9161, 0.9040, 1.9849, 1.9526, 1.8139, 1.3221, 1.7757],
         [1.9679, 0.8414, 1.4654, 0.7867, 2.2469, 1.3771, 1.6252, 2.3525],
         [1.0176, 1.6061, 1.6777, 2.4566, 1.4945, 1.0139, 1.3958, 3.2499],
         [1.6652, 2.2066, 2.0437, 1.7641, 1.8917, 3.1331, 1.6696, 2.2509],
         [2.7801, 2.529

In [32]:
error_7 = torch.nn.functional.mse_loss(output_7,output_7_)
error_7

<ipython-input-32-eb177f28b4f7>:1: UserWarning: Using a target size (torch.Size([3, 8, 8])) that is different to the input size (torch.Size([1, 3, 8, 8])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  error_7 = torch.nn.functional.mse_loss(output_7,output_7_)


tensor(0.)

## Function 8: torch.nn.functional.batch_norm

In [33]:
running_mean = torch.zeros(3)+1
running_var = torch.ones(3)*2
output_8 = torch.nn.functional.batch_norm(Input, running_mean, running_var, weight=None, bias=None, training=False, momentum=0.1, eps=1e-05)
output_8

tensor([[[[-1.2416e+00,  7.3446e-01,  2.0387e-02,  ..., -2.1558e+00,
           -1.7102e+00,  4.3403e-02],
          [-1.2454e+00, -5.7555e-01,  2.7227e-01,  ..., -5.1074e-01,
           -1.3082e+00,  2.3091e-04],
          [-1.2050e+00, -2.3240e+00, -3.6459e-02,  ..., -1.4820e+00,
            3.7512e-02, -8.0426e-01],
          ...,
          [-3.6764e-01,  2.3379e-02, -1.5200e+00,  ..., -1.0668e+00,
           -1.8110e+00,  3.8995e-02],
          [-1.8203e-01, -2.9881e-01,  5.5161e-01,  ..., -1.2416e+00,
           -1.3405e+00, -1.3596e+00],
          [-6.9060e-01, -2.1927e-01,  1.0831e-01,  ..., -1.2429e-01,
            9.7819e-01, -1.2318e+00]],

         [[-1.6829e+00, -1.1619e+00, -1.5610e+00,  ..., -4.2357e-01,
           -4.2349e-01, -9.3827e-01],
          [-3.8548e-01,  4.7217e-01,  5.6462e-01,  ..., -1.2476e+00,
            1.2023e-01, -3.4921e-01],
          [-3.4135e-01, -7.9624e-01, -6.9056e-01,  ...,  2.1663e-01,
           -4.7694e-01, -7.3532e-01],
          ...,
     

In [34]:
def batchnorm(input, running_mean, running_var, momentum=0.1, eps=1e-05):
    mean = running_mean
    var = running_var
    mean, var = mean[:,None,None],var[:,None,None]
    
    return (input-mean) / torch.sqrt(var+eps)

In [35]:
output_8_ = batchnorm(Input, running_mean, running_var, momentum=0.1, eps=1e-05)
output_8_

tensor([[[[-1.2416e+00,  7.3446e-01,  2.0387e-02,  ..., -2.1558e+00,
           -1.7102e+00,  4.3403e-02],
          [-1.2454e+00, -5.7555e-01,  2.7227e-01,  ..., -5.1074e-01,
           -1.3082e+00,  2.3088e-04],
          [-1.2050e+00, -2.3240e+00, -3.6459e-02,  ..., -1.4820e+00,
            3.7512e-02, -8.0426e-01],
          ...,
          [-3.6764e-01,  2.3379e-02, -1.5200e+00,  ..., -1.0668e+00,
           -1.8110e+00,  3.8995e-02],
          [-1.8203e-01, -2.9881e-01,  5.5161e-01,  ..., -1.2416e+00,
           -1.3405e+00, -1.3596e+00],
          [-6.9060e-01, -2.1927e-01,  1.0831e-01,  ..., -1.2429e-01,
            9.7819e-01, -1.2318e+00]],

         [[-1.6829e+00, -1.1619e+00, -1.5610e+00,  ..., -4.2357e-01,
           -4.2349e-01, -9.3827e-01],
          [-3.8548e-01,  4.7217e-01,  5.6462e-01,  ..., -1.2476e+00,
            1.2023e-01, -3.4921e-01],
          [-3.4135e-01, -7.9624e-01, -6.9056e-01,  ...,  2.1663e-01,
           -4.7694e-01, -7.3532e-01],
          ...,
     

In [36]:
error_8 = torch.nn.functional.mse_loss(output_8,output_8_)
error_8

tensor(4.0974e-15)

## Function 9: torch.nn.functional.cross_entropy

In [37]:
target = torch.randint(0,3, (1,32,32), dtype=torch.int64)
target

tensor([[[1, 2, 2,  ..., 2, 2, 1],
         [0, 0, 0,  ..., 2, 1, 2],
         [2, 2, 2,  ..., 2, 0, 0],
         ...,
         [0, 0, 1,  ..., 2, 2, 0],
         [1, 0, 2,  ..., 2, 2, 2],
         [0, 0, 1,  ..., 0, 1, 1]]])

In [38]:
output_9 = torch.nn.functional.cross_entropy(Input, target,weight=None, size_average=None, ignore_index=-100, reduce=None, reduction='mean')
output_9

tensor(1.3724)

In [39]:
def softmax(x):
    maxes = torch.max(x, 1, keepdim=True)[0]
    x_exp = torch.exp(x-maxes)
    x_exp_sum = torch.sum(x_exp, 1, keepdim=True)

    return x_exp/x_exp_sum

In [40]:
Input_softmax = np.array(softmax(Input)[0])
target = np.array(target)
loss = 0.0
for b in range(target.shape[0]):
    for i in range(target.shape[1]):
        for j in range(target.shape[2]):
            loss -= np.log(Input_softmax[target[b][i][j]][i][j])/1024
print(torch.tensor(loss))  

tensor(1.3724, dtype=torch.float64)


## Function 10: torch.nn.functional.mse_loss

In [41]:
target = torch.randn(1,3,32,32)
output_10 = torch.nn.functional.mse_loss(Input, target, size_average=None, reduce=None, reduction='mean')
output_10

tensor(1.9899)

In [42]:
def mse(inp,target):
    MSE = np.square(np.subtract(inp,target)).mean()
    return MSE

In [43]:
output_10_ = mse(Input, target)
output_10_

tensor(1.9899)